### PR TITLE
fix: stack validation

### LINKED ISSUE #34: Tests not passing
Hi, I'm really excited about Stacks

But I tried to deploy the grunge Stack as it says in the README itself and after installing the tests idoesn't pass.

 **Tests that not pass**
    1) should allow you to register and login
    2) should allow you to make a note

**Gist with the errors**
https://gist.github.com/JoaoGomes5/7cfa976ae9672ab5e7bd4c255ec7677a

I followed the tutorial video [](https://www.youtube.com/watch?v=J9sHle5Q8ME) and it gives me an error right at the beginning, I don't understand why.

I already tried to create new projects and all of them did not pass the tests.

Thanks and have a great day!

### PR DESCRIPTION
**Pull request by salper**
This should fix #34

### CODE REVIEW

File: cypress/support/test-routes/create-user.ts [hunk 1]
```diff
@@ -31,3 +31,5 @@ export const action: ActionFunction = async ({ request }) => {
     redirectTo: "/",
   });
 };
+
+export default null;
```
Comment (salper) [inline cypress/support/test-routes/create-user.ts:35]: Without it, tree shaking does not work properly.

**Review by kentcdodds — APPROVED** [review]
Thanks!
